// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gufvtnbdhpvrnfelxzjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1ZnZ0bmJkaHB2cm5mZWx4empsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NzkxODIsImV4cCI6MjA1MjI1NTE4Mn0.3eAvyiB_oZKNVoVin6K2oU3UX-qCkzyQy_sW7Bhlrjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);